import * as React from "react";
import * as ReactDOM from "react-dom";
import * as SemanticUI from "semantic-ui-react";
import * as ReactMonacoEditor from "react-monaco-editor";
import BaseObject from "./objects/base/BaseObject";
import BaseUI from "./objects/base/BaseUI";
import DefaultObject from "./objects/base/DefaultObject";
import DefaultUI from "./objects/base/DefaultUI";
import CanvasUI from "./objects/base/CanvasUI";
import CodeUI from "./objects/base/CodeUI";
import CommentUI from "./objects/base/CommentUI";
import DefaultPopupUI from "./objects/base/DefaultPopupUI";
import CodePopupUI from "./objects/base/CodePopupUI";
import DOMUI from "./objects/base/DOMUI";
import PatcherAudio from "./audio/PatcherAudio";
import OperableAudioBuffer from "./audio/OperableAudioBuffer";
import Patcher from "./patcher/Patcher";
import Box from "./patcher/Box";
import Line from "./patcher/Line";
import generateRemoteObject from "./objects/base/generateRemoteObject";
import generateRemotedObject from "./objects/base/generateRemotedObject";
import generateDefaultObject from "./objects/base/generateDefaultObject";
import Bang, { isBang } from "./objects/base/Bang";
import TransmitterNode from "./worklets/Transmitter";
import TemporalAnalyserNode from "./worklets/TemporalAnalyser";
import SpectralAnalyserNode from "./worklets/SpectralAnalyser";
import * as MathUtils from "../utils/math";
import * as BufferUtils from "../utils/buffer";
import * as Utils from "../utils/utils";
import Importer from "./objects/importer/Importer";
import DefaultImporter from "./objects/importer/DefaultImporter";
import RemoteImporter from "./objects/importer/RemoteImporter";
import RemotedImporter from "./objects/importer/RemotedImporter";

export interface IJSPatcherSDK {
    readonly React?: typeof React;
    readonly ReactDOM?: typeof ReactDOM;
    readonly SemanticUI?: typeof SemanticUI;
    readonly PatcherAudio?: typeof PatcherAudio;
    readonly OperableAudioBuffer?: typeof OperableAudioBuffer;
    readonly Patcher: typeof Patcher;
    readonly Box: typeof Box;
    readonly Line: typeof Line;
    readonly BaseObject: typeof BaseObject;
    readonly DefaultObject?: typeof DefaultObject;
    readonly BaseUI?: typeof BaseUI;
    readonly DefaultUI?: typeof DefaultUI;
    readonly CanvasUI?: typeof CanvasUI;
    readonly CodeUI?: typeof CodeUI;
    readonly CommentUI?: typeof CommentUI;
    readonly DefaultPopupUI?: typeof DefaultPopupUI;
    readonly CodePopupUI?: typeof CodePopupUI;
    readonly DOMUI?: typeof DOMUI;
    readonly generateDefaultObject?: typeof generateDefaultObject;
    readonly generateRemoteObject?: typeof generateRemoteObject;
    readonly generateRemotedObject: typeof generateRemotedObject;
    readonly Bang: typeof Bang;
    readonly isBang: typeof isBang;
    readonly TransmitterNode?: typeof TransmitterNode;
    readonly TemporalAnalyserNode?: typeof TemporalAnalyserNode;
    readonly SpectralAnalyserNode?: typeof SpectralAnalyserNode;
    readonly MathUtils: typeof MathUtils;
    readonly BufferUtils: typeof BufferUtils;
    readonly Utils: typeof Utils;
    readonly Importer: typeof Importer;
    readonly DefaultImporter?: typeof DefaultImporter;
    readonly RemoteImporter?: typeof RemoteImporter;
    readonly RemotedImporter: typeof RemotedImporter;
    getReactMonacoEditor?(): Promise<typeof ReactMonacoEditor>;
}

export default class JSPatcherSDK implements IJSPatcherSDK {
    readonly React = React;
    readonly ReactDOM = ReactDOM;
    readonly SemanticUI = SemanticUI;
    readonly PatcherAudio = PatcherAudio;
    readonly OperableAudioBuffer = OperableAudioBuffer;
    readonly Patcher = Patcher;
    readonly Box = Box;
    readonly Line = Line;
    readonly BaseObject = BaseObject;
    readonly DefaultObject = DefaultObject;
    readonly BaseUI = BaseUI;
    readonly DefaultUI = DefaultUI;
    readonly CanvasUI = CanvasUI;
    readonly CodeUI = CodeUI;
    readonly CommentUI = CommentUI;
    readonly DefaultPopupUI = DefaultPopupUI;
    readonly CodePopupUI = CodePopupUI;
    readonly DOMUI = DOMUI;
    readonly generateDefaultObject = generateDefaultObject;
    readonly generateRemoteObject = generateRemoteObject;
    readonly generateRemotedObject = generateRemotedObject;
    readonly Bang = Bang;
    readonly isBang = isBang;
    readonly TransmitterNode = TransmitterNode;
    readonly TemporalAnalyserNode = TemporalAnalyserNode;
    readonly SpectralAnalyserNode = SpectralAnalyserNode;
    readonly MathUtils = MathUtils;
    readonly BufferUtils = BufferUtils;
    readonly Utils = Utils;
    readonly Importer = Importer;
    readonly DefaultImporter = DefaultImporter;
    readonly RemoteImporter = RemoteImporter;
    readonly RemotedImporter = RemotedImporter;
    getReactMonacoEditor() { return import("react-monaco-editor"); }
}
